export const THEME='THEME';
export const SHOWFORM='SHOWFORM'
export const SHOWLOGIN='SHOWLOGIN'
export const SHOWSECONDPAGE='SHOWSECONDPAGE'
export const SHOWTHIRDPAGE='SHOWTHIRDPAGE'
export const SHOWFOURTHPAGE='SHOWFOURTHPAGE'


